# Generated by Django 3.2.6 on 2021-09-11 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('pregunta', models.BooleanField()),
                ('eliminar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppWeb.nombre')),
            ],
        ),
    ]
